freebsd_instance:
  image_family: freebsd-13-1

task:
  env:
    matrix:
      - LISP: sbcl
      - LISP: ccl
  preinstall_script:
    - pkg install -y curl libjpeg-turbo sdl2 sdl2_image sdl2_ttf
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
    - cl -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
  script:
    - cl -f $CIRRUS_WORKING_DIR/tests/travis.lisp
