name: CI

on: [push, pull_request]

jobs:
  test_and_docs:
    runs-on: ubuntu-latest
    env:
      LISP: sbcl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install info install-info libturbojpeg0-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          qlot install
          qlot exec ros -l tests/travis.lisp
